<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>std::nested_exception</title>
    <style>
        body { font-family: monospace; margin: 20px; line-height: 1.4; }
        a { color: #0066cc; }
        pre { white-space: pre-wrap; }
    </style>
</head>
<body>
    <div id="main-content">
<section class="p-strip is-bordered">
<div class="row">
<div class="col-3 u-hide--small u-hide" id="toc">
</div>
<div id="tableWrapper">
<p id="distroAndSection"></p>

Provided by: <a href="https://launchpad.net/ubuntu/questing/+package/libstdc++-13-doc">libstdc++-13-doc_13.4.0-1ubuntu1_all</a> <br><br><pre>
</pre><h4><b>NAME</b></h4><pre>
       std::nested_exception

</pre><h4><b>SYNOPSIS</b></h4><pre>
       #include &lt;exception&gt;

   <b>Public</b> <b>Member</b> <b>Functions</b>
       <b>nested_exception</b> () noexcept
           The default constructor stores the current exception (if any).
       <b>nested_exception</b> (const <b>nested_exception</b> &amp;) noexcept=<b>default</b>
       <b>exception_ptr</b> <b>nested_ptr</b> () const noexcept
           Access the stored exception.
       <b>nested_exception</b> &amp; <b>operator=</b> (const <b>nested_exception</b> &amp;) noexcept=<b>default</b>
       <b>void</b> <b>rethrow_nested</b> () const
           Rethrow the stored exception, or terminate if none was stored.

</pre><h4><b>Detailed</b> <b>Description</b></h4><pre>
       Mixin class that stores the current exception.

       This type can be used via std::throw_with_nested to store the current exception nested within another
       exception.

       <b>Since</b>
           C++11

       <b>See</b> <b>also</b>
           std::throw_with_nested

</pre><h4><b>Constructor</b> <b>&amp;</b> <b>Destructor</b> <b>Documentation</b></h4><pre>
   <b>std::nested_exception::nested_exception</b> <b>()</b> <b>[inline],</b>  <b>[noexcept]</b>
       The default constructor stores the current exception (if any).

</pre><h4><b>Member</b> <b>Function</b> <b>Documentation</b></h4><pre>
   <b>exception_ptr</b> <b>std::nested_exception::nested_ptr</b> <b>()</b> <b>const</b> <b>[inline],</b>  <b>[noexcept]</b>
       Access the stored exception.

   <b>void</b> <b>std::nested_exception::rethrow_nested</b> <b>()</b> <b>const</b> <b>[inline]</b>
       Rethrow the stored exception, or terminate if none was stored.

       References <b>std::rethrow_exception()</b>, and <b>std::terminate()</b>.

</pre><h4><b>Author</b></h4><pre>
       Generated automatically by Doxygen for libstdc++ from the source code.

                                                    libstdc++                        <u>std::<a href="../man3cxx/nested_exception.3cxx.html">nested_exception</a></u>(3cxx)
</pre>
 </div>
</div></section>
</div>
</body>
</html>