<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>"Future::Exception" - an exception type for failed Futures</title>
    <style>
        body { font-family: monospace; margin: 20px; line-height: 1.4; }
        a { color: #0066cc; }
        pre { white-space: pre-wrap; }
    </style>
</head>
<body>
    <div id="main-content">
<section class="p-strip is-bordered">
<div class="row">
<div class="col-3 u-hide--small u-hide" id="toc">
</div>
<div id="tableWrapper">
<p id="distroAndSection"></p>

Provided by: <a href="https://launchpad.net/ubuntu/questing/+package/libfuture-perl">libfuture-perl_0.51-1_all</a> <br><br><pre>
</pre><h4><b>NAME</b></h4><pre>
       "Future::Exception" - an exception type for failed Futures

</pre><h4><b>SYNOPSIS</b></h4><pre>
          use Scalar::Util qw( blessed );
          use Syntax::Keyword::Try;

          try {
             my $f = ...;
             my @result = $f-&gt;result;
             ...
          }
          catch {
             if( blessed($@) and $@-&gt;isa( "Future::Exception" ) {
                print STDERR "The ", $@-&gt;category, " failed: ", $@-&gt;message, "\n";
             }
          }

</pre><h4><b>DESCRIPTION</b></h4><pre>
       The "get" method on a failed Future instance will throw an exception to indicate that the future failed.
       A failed future can contain a failure category name and other details as well as the failure message, so
       in this case the exception will be an instance of "Future::Exception" to make these values accessible.

       Users should not depend on exact class name matches, but instead rely on inheritence, as a later version
       of this implementation might dynamically create subclasses whose names are derived from the Future
       failure category string, to assist with type matching. Note the use of "-&gt;isa" in the SYNOPSIS example.

</pre><h4><b>CONSTRUCTOR</b></h4><pre>
   <b>from_future</b>
          $e = Future::Exception-&gt;from_future( $f );

       Constructs a new "Future::Exception" wrapping the given failed future.

</pre><h4><b>ACCESSORS</b></h4><pre>
          $message  = $e-&gt;message;
          $category = $e-&gt;category;
          @details  = $e-&gt;details;

       Additionally, the object will stringify to return the message value, for the common use-case of printing,
       regexp testing, or other behaviours.

</pre><h4><b>METHODS</b></h4><pre>
   <b>throw</b>
          Future::Exception-&gt;throw( $message, $category, @details );

       <u>Since</u> <u>version</u> <u>0.41.</u>

       Constructs a new exception object and throws it using die(). This method will not return, as it raises
       the exception directly.

       If $message does not end in a linefeed then the calling file and line number are appended to it, in the
       same way die() does.

   <b>as_future</b>
          $f = $e-&gt;as_future;

       Returns a new "Future" object in a failed state matching the exception.

</pre><h4><b>AUTHOR</b></h4><pre>
       Paul Evans &lt;<a href="mailto:leonerd@leonerd.org.uk">leonerd@leonerd.org.uk</a>&gt;

perl v5.40.0                                       2024-10-26                             <u>Future::<a href="../man3pm/Exception.3pm.html">Exception</a></u>(3pm)
</pre>
 </div>
</div></section>
</div>
</body>
</html>